# Generated by Django 3.1.5 on 2021-01-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='idr_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='kva',
            field=models.FloatField(help_text='Please enter the number in kVA'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='value',
            field=models.FloatField(help_text='Please insert the price in chosen foreign currency'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='capacity',
            field=models.FloatField(help_text='Please insert the value in Ah.'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='idr_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='battery',
            name='kwh',
            field=models.FloatField(help_text='Please insert the value in KWh.'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='v_per_cell',
            field=models.FloatField(help_text='Please insert the value in Volt per Cell.'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='value',
            field=models.FloatField(help_text='Please insert the price in chosen foreign currency.'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='idr_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='kva',
            field=models.FloatField(help_text='Please enter the number in kVA'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='value',
            field=models.FloatField(help_text='Please insert the price in chosen foreign currency'),
        ),
        migrations.AlterField(
            model_name='lvpanel',
            name='usd_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='usd_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mounting',
            name='kw_value',
            field=models.FloatField(help_text='Please insert the value in Wp.'),
        ),
        migrations.AlterField(
            model_name='mounting',
            name='wp_price',
            field=models.FloatField(help_text='Please insert the price per Wp in USD.'),
        ),
        migrations.AlterField(
            model_name='mvpanel',
            name='usd_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='kw_value',
            field=models.FloatField(help_text='Please insert the value in Wp.'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='wp_price',
            field=models.FloatField(help_text='Please insert the price per Wp in USD.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='usd_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solarcc',
            name='amperage',
            field=models.FloatField(help_text='Please insert the value in Ampere.'),
        ),
        migrations.AlterField(
            model_name='solarcc',
            name='idr_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solarcc',
            name='value',
            field=models.FloatField(help_text='Please insert the price in chosen foreign currency.'),
        ),
        migrations.AlterField(
            model_name='solarcc',
            name='vbat',
            field=models.FloatField(help_text='Please insert the value in Volt.'),
        ),
        migrations.AlterField(
            model_name='solarcc',
            name='wattmax',
            field=models.FloatField(help_text='Please insert the value in Watt.'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='kva_value',
            field=models.FloatField(help_text='Please insert the value in kVA.'),
        ),
        migrations.AlterField(
            model_name='trafo',
            name='usd_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='usd_value',
            field=models.FloatField(),
        ),
    ]
